### ISSUE TITLE
Re-arrange the patterns according to their difficulty level, starting from easy to hard

### ISSUE THREAD

**Issue by Bhavana-Jami** [Bhavana-Jami/javascript_pattern_programs#1]
I have added the pattern programs randomly whenever I practiced, please arrange them according to the difficulty both the programs and images.
Starting from pattern1, should be the easy one and change the .js file name accordingly if you are re arranging the patterns. Please cross check the outputs once re-arranged.

**Comment by munnavuyyuru** [comment]
working on it

**Comment by Bhavana-Jami** [comment]
Sure

**Comment by munnavuyyuru** [comment]
fixes done

**Comment by Bhavana-Jami** [comment]
Thanks.
